from __future__ import annotations

from typing import Any, Optional

from .streams import Event as Event
from .streams import Stream as Stream

def current_stream(device: Any | None = ...): ...
def synchronize(device: Any | None = ...): ...
def device_count(): ...
def empty_cache() -> None: ...
def max_memory_allocated(device: Any | None = ...): ...
def max_memory_reserved(device: Any | None = ...): ...
def memory_allocated(device: Any | None = ...): ...
def memory_reserved(device: Any | None = ...): ...
def stream_guard(stream: Any) -> None: ...
def get_device_properties(device: Any | None = ...): ...
def get_device_name(device: Any | None = ...): ...
def get_device_capability(device: Any | None = ...): ...
