from __future__ import annotations

from typing import Any

from paddle.utils import gast

class PrintTransformer(gast.NodeTransformer):
    wrapper_root: Any = ...
    root: Any = ...
    static_analysis_visitor: Any = ...
    node_to_wrapper_map: Any = ...
    def __init__(self, wrapper_root: Any) -> None: ...
    def transform(self) -> None: ...
    def visit_Call(self, node: Any): ...
    def visit_Print(self, node: Any): ...
