from __future__ import annotations

from ._alexnet import AlexNet as AlexNet
from ._alexnet import alexnet as alexnet
from ._densenet import DenseNet as DenseNet
from ._densenet import densenet121 as densenet121
from ._densenet import densenet161 as densenet161
from ._densenet import densenet169 as densenet169
from ._densenet import densenet201 as densenet201
from ._densenet import densenet264 as densenet264
from ._googlenet import GoogLeNet as GoogLeNet
from ._googlenet import googlenet as googlenet
from ._inceptionv3 import InceptionV3 as InceptionV3
from ._inceptionv3 import inception_v3 as inception_v3
from ._lenet import LeNet as LeNet
from ._mobilenetv1 import MobileNetV1 as MobileNetV1
from ._mobilenetv1 import mobilenet_v1 as mobilenet_v1
from ._mobilenetv2 import MobileNetV2 as MobileNetV2
from ._mobilenetv2 import mobilenet_v2 as mobilenet_v2
from ._mobilenetv3 import MobileNetV3Large as MobileNetV3Large
from ._mobilenetv3 import MobileNetV3Small as MobileNetV3Small
from ._mobilenetv3 import mobilenet_v3_large as mobilenet_v3_large
from ._mobilenetv3 import mobilenet_v3_small as mobilenet_v3_small
from ._resnet import ResNet as ResNet
from ._resnet import resnet18 as resnet18
from ._resnet import resnet34 as resnet34
from ._resnet import resnet50 as resnet50
from ._resnet import resnet101 as resnet101
from ._resnet import resnet152 as resnet152
from ._resnet import resnext50_32x4d as resnext50_32x4d
from ._resnet import resnext50_64x4d as resnext50_64x4d
from ._resnet import resnext101_32x4d as resnext101_32x4d
from ._resnet import resnext101_64x4d as resnext101_64x4d
from ._resnet import resnext152_32x4d as resnext152_32x4d
from ._resnet import resnext152_64x4d as resnext152_64x4d
from ._resnet import wide_resnet50_2 as wide_resnet50_2
from ._resnet import wide_resnet101_2 as wide_resnet101_2
from ._shufflenetv2 import ShuffleNetV2 as ShuffleNetV2
from ._shufflenetv2 import shufflenet_v2_swish as shufflenet_v2_swish
from ._shufflenetv2 import shufflenet_v2_x0_5 as shufflenet_v2_x0_5
from ._shufflenetv2 import shufflenet_v2_x0_25 as shufflenet_v2_x0_25
from ._shufflenetv2 import shufflenet_v2_x0_33 as shufflenet_v2_x0_33
from ._shufflenetv2 import shufflenet_v2_x1_0 as shufflenet_v2_x1_0
from ._shufflenetv2 import shufflenet_v2_x1_5 as shufflenet_v2_x1_5
from ._shufflenetv2 import shufflenet_v2_x2_0 as shufflenet_v2_x2_0
from ._squeezenet import SqueezeNet as SqueezeNet
from ._squeezenet import squeezenet1_0 as squeezenet1_0
from ._squeezenet import squeezenet1_1 as squeezenet1_1
from ._vgg import VGG as VGG
from ._vgg import vgg11 as vgg11
from ._vgg import vgg13 as vgg13
from ._vgg import vgg16 as vgg16
from ._vgg import vgg19 as vgg19
