from __future__ import annotations

from typing import Any

import paddle.nn as nn

class LeNet(nn.Layer):
    num_classes: Any = ...
    features: Any = ...
    fc: Any = ...
    def __init__(self, num_classes: int = ...) -> None: ...
    def forward(self, inputs: Any): ...
