from __future__ import annotations

from typing import Any

import paddle.nn as nn

from ..ops import ConvNormActivation as ConvNormActivation

model_urls: Any

class DepthwiseSeparable(nn.Layer):
    def __init__(
        self, in_channels: Any, out_channels1: Any, out_channels2: Any, num_groups: Any, stride: Any, scale: Any
    ) -> None: ...
    def forward(self, x: Any): ...

class MobileNetV1(nn.Layer):
    scale: Any = ...
    dwsl: Any = ...
    num_classes: Any = ...
    with_pool: Any = ...
    conv1: Any = ...
    pool2d_avg: Any = ...
    fc: Any = ...
    def __init__(self, scale: float = ..., num_classes: int = ..., with_pool: bool = ...) -> None: ...
    def forward(self, x: Any): ...

def mobilenet_v1(pretrained: bool = ..., scale: float = ..., **kwargs: Any): ...
