from __future__ import annotations

from typing import Any

import paddle.nn as nn

from ..ops import ConvNormActivation as ConvNormActivation

model_urls: Any

class InvertedResidual(nn.Layer):
    stride: Any = ...
    use_res_connect: Any = ...
    conv: Any = ...
    def __init__(self, inp: Any, oup: Any, stride: Any, expand_ratio: Any, norm_layer: Any = ...) -> None: ...
    def forward(self, x: Any): ...

class MobileNetV2(nn.Layer):
    num_classes: Any = ...
    with_pool: Any = ...
    last_channel: Any = ...
    features: Any = ...
    pool2d_avg: Any = ...
    classifier: Any = ...
    def __init__(self, scale: float = ..., num_classes: int = ..., with_pool: bool = ...) -> None: ...
    def forward(self, x: Any): ...

def mobilenet_v2(pretrained: bool = ..., scale: float = ..., **kwargs: Any): ...
