from __future__ import annotations

from typing import Any

import paddle.nn as nn

model_urls: Any

class VGG(nn.Layer):
    features: Any = ...
    num_classes: Any = ...
    with_pool: Any = ...
    avgpool: Any = ...
    classifier: Any = ...
    def __init__(self, features: Any, num_classes: int = ..., with_pool: bool = ...) -> None: ...
    def forward(self, x: Any): ...

def make_layers(cfg: Any, batch_norm: bool = ...): ...

cfgs: Any

def vgg11(pretrained: bool = ..., batch_norm: bool = ..., **kwargs: Any): ...
def vgg13(pretrained: bool = ..., batch_norm: bool = ..., **kwargs: Any): ...
def vgg16(pretrained: bool = ..., batch_norm: bool = ..., **kwargs: Any): ...
def vgg19(pretrained: bool = ..., batch_norm: bool = ..., **kwargs: Any): ...
