from __future__ import annotations

from typing import Any, Optional

from paddle.nn import Layer

from ...framework import ParamAttr as ParamAttr
from ..initializer import Constant as Constant

class CELU(Layer):
    def __init__(self, alpha: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class ELU(Layer):
    def __init__(self, alpha: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class GELU(Layer):
    def __init__(self, approximate: bool = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Hardshrink(Layer):
    def __init__(self, threshold: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Hardswish(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Tanh(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Hardtanh(Layer):
    def __init__(self, min: Any = ..., max: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class PReLU(Layer):
    def __init__(
        self,
        num_parameters: int = ...,
        init: float = ...,
        weight_attr: Optional[Any] = ...,
        data_format: str = ...,
        name: Optional[Any] = ...,
    ) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class ReLU(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class ReLU6(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class SELU(Layer):
    def __init__(self, scale: float = ..., alpha: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class LeakyReLU(Layer):
    def __init__(self, negative_slope: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Sigmoid(Layer):
    name: Any = ...
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Hardsigmoid(Layer):
    name: Any = ...
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Softplus(Layer):
    def __init__(self, beta: int = ..., threshold: int = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Softshrink(Layer):
    def __init__(self, threshold: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Softsign(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Swish(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Mish(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Tanhshrink(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class ThresholdedReLU(Layer):
    def __init__(self, threshold: float = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Silu(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class LogSigmoid(Layer):
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Softmax(Layer):
    def __init__(self, axis: int = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class LogSoftmax(Layer):
    def __init__(self, axis: int = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self): ...

class Maxout(Layer):
    def __init__(self, groups: Any, axis: int = ..., name: Optional[Any] = ...) -> None: ...
    def forward(self, x: Any): ...
    def extra_repr(self) -> str: ...
