from __future__ import annotations

from typing import Any, Optional

from paddle.fluid.incubate.fleet.base.fleet_base import DistributedOptimizer, Fleet
from paddle.fluid.incubate.fleet.parameter_server.distribute_transpiler.distributed_strategy import (
    TrainerRuntimeConfig as TrainerRuntimeConfig,
)

class FleetTranspiler(Fleet):
    startup_program: Any = ...
    main_program: Any = ...
    def __init__(self) -> None: ...
    def init(self, role_maker: Any | None = ...) -> None: ...
    def init_worker(self) -> None: ...
    def init_server(self, model_dir: Any | None = ..., **kwargs: Any) -> None: ...
    def run_server(self) -> None: ...
    def stop_worker(self) -> None: ...
    def distributed_optimizer(self, optimizer: Any, strategy: Any | None = ...): ...
    def save_inference_model(
        self,
        executor: Any,
        dirname: Any,
        feeded_var_names: Any,
        target_vars: Any,
        main_program: Any | None = ...,
        export_for_deployment: bool = ...,
    ) -> None: ...
    def save_persistables(self, executor: Any, dirname: Any, main_program: Any | None = ..., **kwargs: Any) -> None: ...

fleet: Any

class ParameterServerOptimizer(DistributedOptimizer):
    type: str = ...
    data_norm_name: Any = ...
    def __init__(self, optimizer: Any, strategy: Any, mode: Any = ...) -> None: ...
    def backward(
        self,
        loss: Any,
        startup_program: Any | None = ...,
        parameter_list: Any | None = ...,
        no_grad_set: Any | None = ...,
        callbacks: Any | None = ...,
    ) -> None: ...
    def apply_gradients(self, params_grads: Any) -> None: ...
    def minimize(
        self,
        losses: Any,
        scopes: Any | None = ...,
        startup_programs: Any | None = ...,
        parameter_list: Any | None = ...,
        no_grad_set: Any | None = ...,
    ) -> None: ...
