from __future__ import annotations

from typing import Any, Optional

from ..fluid import layers as layers
from ..fluid.data_feeder import check_dtype as check_dtype
from ..fluid.data_feeder import check_type as check_type
from ..fluid.data_feeder import check_variable_and_dtype as check_variable_and_dtype
from ..fluid.framework import in_dygraph_mode as in_dygraph_mode
from ..fluid.layer_helper import LayerHelper as LayerHelper
from ..framework import core as core
from .logic import logical_not as logical_not

def argsort(x: Any, axis: int = ..., descending: bool = ..., name: str | None = ...): ...
def argmax(x: Any, axis: Any | None = ..., keepdim: bool = ..., dtype: str = ..., name: str | None = ...): ...
def argmin(x: Any, axis: Any | None = ..., keepdim: bool = ..., dtype: str = ..., name: str | None = ...): ...
def index_select(x: Any, index: Any, axis: int = ..., name: str | None = ...): ...
def nonzero(x: Any, as_tuple: bool = ...): ...
def sort(x: Any, axis: int = ..., descending: bool = ..., name: str | None = ...): ...
def mode(x: Any, axis: int = ..., keepdim: bool = ..., name: str | None = ...): ...
def where(condition: Any, x: Any | None = ..., y: Any | None = ..., name: str | None = ...): ...
def index_sample(x: Any, index: Any): ...
def masked_select(x: Any, mask: Any, name: str | None = ...): ...
def topk(x: Any, k: Any, axis: Any | None = ..., largest: bool = ..., sorted: bool = ..., name: str | None = ...): ...
def searchsorted(
    sorted_sequence: Any, values: Any, out_int32: bool = ..., right: bool = ..., name: str | None = ...
): ...
def kthvalue(x: Any, k: Any, axis: Any | None = ..., keepdim: bool = ..., name: str | None = ...): ...
