from __future__ import annotations

from typing import Any, Optional

from .._typing import IntSequence, Tensor

def mean(
    x: Tensor,
    axis: int | IntSequence | None = ...,
    keepdim: bool = ...,
    name: str | None = ...,
) -> Tensor: ...
def var(x: Any, axis: Any | None = ..., unbiased: bool = ..., keepdim: bool = ..., name: str | None = ...): ...
def std(x: Any, axis: Any | None = ..., unbiased: bool = ..., keepdim: bool = ..., name: str | None = ...): ...
def numel(x: Any, name: str | None = ...): ...
def median(x: Any, axis: Any | None = ..., keepdim: bool = ..., name: str | None = ...): ...
def quantile(x: Any, q: Any, axis: Any | None = ..., keepdim: bool = ...): ...
