from __future__ import annotations

from typing import Any, Optional

def sum(input: Any, scope: Any | None = ..., util: Any | None = ...): ...
def max(input: Any, scope: Any | None = ..., util: Any | None = ...): ...
def min(input: Any, scope: Any | None = ..., util: Any | None = ...): ...
def auc(stat_pos: Any, stat_neg: Any, scope: Any | None = ..., util: Any | None = ...): ...
def mae(abserr: Any, total_ins_num: Any, scope: Any | None = ..., util: Any | None = ...): ...
def rmse(sqrerr: Any, total_ins_num: Any, scope: Any | None = ..., util: Any | None = ...): ...
def mse(sqrerr: Any, total_ins_num: Any, scope: Any | None = ..., util: Any | None = ...): ...
def acc(correct: Any, total: Any, scope: Any | None = ..., util: Any | None = ...): ...
