from __future__ import annotations

from typing import Any, Optional

def fft(x: Any, n: Any | None = ..., axis: int = ..., norm: str = ..., name: str | None = ...): ...
def ifft(x: Any, n: Any | None = ..., axis: int = ..., norm: str = ..., name: str | None = ...): ...
def rfft(x: Any, n: Any | None = ..., axis: int = ..., norm: str = ..., name: str | None = ...): ...
def irfft(x: Any, n: Any | None = ..., axis: int = ..., norm: str = ..., name: str | None = ...): ...
def hfft(x: Any, n: Any | None = ..., axis: int = ..., norm: str = ..., name: str | None = ...): ...
def ihfft(x: Any, n: Any | None = ..., axis: int = ..., norm: str = ..., name: str | None = ...): ...
def fftn(x: Any, s: Any | None = ..., axes: Any | None = ..., norm: str = ..., name: str | None = ...): ...
def ifftn(x: Any, s: Any | None = ..., axes: Any | None = ..., norm: str = ..., name: str | None = ...): ...
def rfftn(x: Any, s: Any | None = ..., axes: Any | None = ..., norm: str = ..., name: str | None = ...): ...
def irfftn(x: Any, s: Any | None = ..., axes: Any | None = ..., norm: str = ..., name: str | None = ...): ...
def hfftn(x: Any, s: Any | None = ..., axes: Any | None = ..., norm: str = ..., name: str | None = ...): ...
def ihfftn(x: Any, s: Any | None = ..., axes: Any | None = ..., norm: str = ..., name: str | None = ...): ...
def fft2(x: Any, s: Any | None = ..., axes: Any = ..., norm: str = ..., name: str | None = ...): ...
def ifft2(x: Any, s: Any | None = ..., axes: Any = ..., norm: str = ..., name: str | None = ...): ...
def rfft2(x: Any, s: Any | None = ..., axes: Any = ..., norm: str = ..., name: str | None = ...): ...
def irfft2(x: Any, s: Any | None = ..., axes: Any = ..., norm: str = ..., name: str | None = ...): ...
def hfft2(x: Any, s: Any | None = ..., axes: Any = ..., norm: str = ..., name: str | None = ...): ...
def ihfft2(x: Any, s: Any | None = ..., axes: Any = ..., norm: str = ..., name: str | None = ...): ...
def fftfreq(n: Any, d: float = ..., dtype: Any | None = ..., name: str | None = ...): ...
def rfftfreq(n: Any, d: float = ..., dtype: Any | None = ..., name: str | None = ...): ...
def fftshift(x: Any, axes: Any | None = ..., name: str | None = ...): ...
def ifftshift(x: Any, axes: Any | None = ..., name: str | None = ...): ...
