from __future__ import annotations

from typing import Any, Optional

def fft(x: Any, n: Optional[Any] = ..., axis: int = ..., norm: str = ..., name: Optional[str] = ...): ...
def ifft(x: Any, n: Optional[Any] = ..., axis: int = ..., norm: str = ..., name: Optional[str] = ...): ...
def rfft(x: Any, n: Optional[Any] = ..., axis: int = ..., norm: str = ..., name: Optional[str] = ...): ...
def irfft(x: Any, n: Optional[Any] = ..., axis: int = ..., norm: str = ..., name: Optional[str] = ...): ...
def hfft(x: Any, n: Optional[Any] = ..., axis: int = ..., norm: str = ..., name: Optional[str] = ...): ...
def ihfft(x: Any, n: Optional[Any] = ..., axis: int = ..., norm: str = ..., name: Optional[str] = ...): ...
def fftn(x: Any, s: Optional[Any] = ..., axes: Optional[Any] = ..., norm: str = ..., name: Optional[str] = ...): ...
def ifftn(x: Any, s: Optional[Any] = ..., axes: Optional[Any] = ..., norm: str = ..., name: Optional[str] = ...): ...
def rfftn(x: Any, s: Optional[Any] = ..., axes: Optional[Any] = ..., norm: str = ..., name: Optional[str] = ...): ...
def irfftn(x: Any, s: Optional[Any] = ..., axes: Optional[Any] = ..., norm: str = ..., name: Optional[str] = ...): ...
def hfftn(x: Any, s: Optional[Any] = ..., axes: Optional[Any] = ..., norm: str = ..., name: Optional[str] = ...): ...
def ihfftn(x: Any, s: Optional[Any] = ..., axes: Optional[Any] = ..., norm: str = ..., name: Optional[str] = ...): ...
def fft2(x: Any, s: Optional[Any] = ..., axes: Any = ..., norm: str = ..., name: Optional[str] = ...): ...
def ifft2(x: Any, s: Optional[Any] = ..., axes: Any = ..., norm: str = ..., name: Optional[str] = ...): ...
def rfft2(x: Any, s: Optional[Any] = ..., axes: Any = ..., norm: str = ..., name: Optional[str] = ...): ...
def irfft2(x: Any, s: Optional[Any] = ..., axes: Any = ..., norm: str = ..., name: Optional[str] = ...): ...
def hfft2(x: Any, s: Optional[Any] = ..., axes: Any = ..., norm: str = ..., name: Optional[str] = ...): ...
def ihfft2(x: Any, s: Optional[Any] = ..., axes: Any = ..., norm: str = ..., name: Optional[str] = ...): ...
def fftfreq(n: Any, d: float = ..., dtype: Optional[Any] = ..., name: Optional[str] = ...): ...
def rfftfreq(n: Any, d: float = ..., dtype: Optional[Any] = ..., name: Optional[str] = ...): ...
def fftshift(x: Any, axes: Optional[Any] = ..., name: Optional[str] = ...): ...
def ifftshift(x: Any, axes: Optional[Any] = ..., name: Optional[str] = ...): ...
