from __future__ import annotations

from typing import Any, Optional

class DistributedInfer:
    origin_main_program: Any = ...
    origin_startup_program: Any = ...
    sparse_table_maps: Any = ...
    def __init__(self, main_program: Any | None = ..., startup_program: Any | None = ...) -> None: ...
    def init_distributed_infer_env(
        self, exe: Any, loss: Any, role_maker: Any | None = ..., dirname: str | None = ...
    ) -> None: ...
    def get_dist_infer_program(self): ...
