from __future__ import annotations

from typing import Any, Optional

def softshrink(x: Any, alpha: Any | None = ...): ...
def hard_shrink(x: Any, threshold: Any | None = ...): ...
def cumsum(x: Any, axis: Any | None = ..., exclusive: Any | None = ..., reverse: Any | None = ...): ...
def thresholded_relu(x: Any, threshold: Any | None = ...): ...
def gelu(x: Any, approximate: bool = ...): ...
def erf(x: Any, name: str | None = ...): ...
