name: black-action

on: [push, pull_request, workflow_dispatch]

jobs:
  linter_name:
    name: black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: ". --line-length 120 --check --diff"
