name: Lint and Format

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only run linter and formatter on minimum supported Python version
        python-version: ['3.8']
        architecture: ['x64']
    name: Python ${{ matrix.python-version }} on ${{ matrix.architecture }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prettier
        run: |
          npm install -g prettier

      - name: Install poetry
        run: pipx install poetry

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          cache: 'poetry'

      - name: Install just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          just ci-install

      - name: lint
        run: |
          just ci-lint

      - name: format check
        run: |
          just ci-fmt-check
