name: Lint and Format

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only run linter and formatter on minimum supported Python version
        python-version: ["3.8"]
        architecture: ["x64"]
    name: Python ${{ matrix.python-version }} on ${{ matrix.architecture }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install prettier
        run: |
          npm install -g prettier

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v3
        id: poetry-cache
        with:
          path: |
            .venv
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: |
          just ci-install

      - name: lint
        run: |
          just ci-lint

      - name: format check
        run: |
          just ci-fmt-check
