from __future__ import annotations

from typing import Any

from paddle.base.framework import in_dygraph_mode as in_dygraph_mode
from paddle.distribution import exponential_family

class Dirichlet(exponential_family.ExponentialFamily):
    concentration: Any = ...
    def __init__(self, concentration: Any) -> None: ...
    @property
    def mean(self): ...
    @property
    def variance(self): ...
    def sample(self, shape: Any = ...): ...
    def prob(self, value: Any): ...
    def log_prob(self, value: Any): ...
    def entropy(self): ...
